apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: sample-go-app
  labels:
    app: postgres
data:
  POSTGRES_DB: sample
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
