version: '3'
services:
  sample-go-app:
    build: .
    container_name: sample-app
    environment:
      APP_PORT: "80"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: "sample"
      GORM_LOG: "true"
      GORM_CONN_MAX_LIFETIME: "2s"
      GORM_CONN_MAX_OPEN: "10"
      GORM_CONN_MAX_IDLE: "5"
    command:
      - ./sample-go-app
    networks:
      - sample-go-app
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    depends_on:
      - postgres
  postgres:
    image: postgres:11
    container_name: sample-db
    environment:
      POSTGRES_DB: sample
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - sample-go-app
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdb:
    driver: local
networks:
  sample-go-app:
    external: true
